name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12.0-alpha.6"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install dev.requirements.txt
        run: |
          pip install -r dev.requirements.txt
      - name: Lint with ruff
        run: |
          ruff .
      - name: Static type checker with mypy
        run: |
          mypy . --exclude venv
      - name: Check formatting with black
        run: |
          black --check .
      - name: Test with pytest
        run: |
          pytest